In [3]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [12]:
torch.arange(3)

tensor([0, 1, 2])

In [ ]:

pe = nn.Embedding(3, 2)

In [6]:
pe(torch.arange(3))

tensor([[-1.0264,  1.1458],
        [ 0.1281,  2.0884],
        [-0.1405, -0.7495]], grad_fn=<EmbeddingBackward0>)

In [9]:
pe(torch.tensor(0))

tensor([-1.0264,  1.1458], grad_fn=<EmbeddingBackward0>)

In [13]:
M = torch.rand(5, 10)

In [14]:
M

tensor([[0.1657, 0.3798, 0.5404, 0.8586, 0.5491, 0.0609, 0.5955, 0.7056, 0.6464,
         0.1408],
        [0.3881, 0.3747, 0.1977, 0.9594, 0.7813, 0.5421, 0.3557, 0.1133, 0.3767,
         0.6400],
        [0.4742, 0.6215, 0.5007, 0.3621, 0.2696, 0.3205, 0.1674, 0.9071, 0.7816,
         0.1727],
        [0.4984, 0.7602, 0.0862, 0.3701, 0.0642, 0.1223, 0.6190, 0.6054, 0.9173,
         0.0300],
        [0.0874, 0.1242, 0.1948, 0.1370, 0.0203, 0.6386, 0.7971, 0.5165, 0.2291,
         0.8669]])