In [3]:
import torch
import matplotlib.pyplot as plt
%matplotlib inline


In [10]:
words = open('names.txt', 'r').read().splitlines()
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [ ]:
# build the dataset

block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words[:5]:
  
  #print(w)
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    #print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append
    
X = torch.tensor(X)
Y = torch.tensor(Y)

In [12]:
C = torch.randn(27, 2)

In [13]:
C[X], C[X].shape

(tensor([[[-2.2494, -0.9791],
          [-2.2494, -0.9791],
          [-2.2494, -0.9791]],
 
         [[-2.2494, -0.9791],
          [-2.2494, -0.9791],
          [-0.5192,  0.1319]],
 
         [[-2.2494, -0.9791],
          [-0.5192,  0.1319],
          [-0.7216,  1.6499]],
 
         [[-0.5192,  0.1319],
          [-0.7216,  1.6499],
          [-0.7216,  1.6499]],
 
         [[-0.7216,  1.6499],
          [-0.7216,  1.6499],
          [ 0.2325, -1.9379]],
 
         [[-2.2494, -0.9791],
          [-2.2494, -0.9791],
          [-2.2494, -0.9791]],
 
         [[-2.2494, -0.9791],
          [-2.2494, -0.9791],
          [ 0.2062,  0.4357]],
 
         [[-2.2494, -0.9791],
          [ 0.2062,  0.4357],
          [ 0.9032,  0.3080]],
 
         [[ 0.2062,  0.4357],
          [ 0.9032,  0.3080],
          [ 1.0489,  0.4129]],
 
         [[ 0.9032,  0.3080],
          [ 1.0489,  0.4129],
          [ 0.6527,  1.0434]],
 
         [[ 1.0489,  0.4129],
          [ 0.6527,  1.0434],
          

In [14]:
C[X][0]

tensor([[-2.2494, -0.9791],
        [-2.2494, -0.9791],
        [-2.2494, -0.9791]])

In [15]:
emb = C[X]

In [17]:
emb[0, :, :]

tensor([[-2.2494, -0.9791],
        [-2.2494, -0.9791],
        [-2.2494, -0.9791]])

In [18]:
W1 = torch.randn(6, 100)
b1 = torch.randn(100)

In [22]:
mm = emb.view(32, -1) @ W1 

In [23]:
mm

tensor([[ 4.4816e+00,  3.0322e+00, -1.0248e+00,  ..., -4.3475e+00,
         -1.5454e-01,  5.1007e-01],
        [ 3.6016e+00,  2.2815e-01,  7.5726e-01,  ..., -2.1109e+00,
          9.3125e-01, -1.1602e+00],
        [ 2.8876e+00,  1.5782e+00,  6.9230e-01,  ..., -1.6618e+00,
         -2.9186e-01,  4.1097e-01],
        ...,
        [ 9.6600e-01, -1.2498e+00,  4.1305e-01,  ...,  8.7004e-01,
          7.9614e-01, -1.4231e+00],
        [-3.1622e-03, -1.0624e+00, -5.1390e-01,  ..., -2.0925e-02,
          2.6674e+00,  2.2476e-01],
        [-2.6596e+00,  5.0515e-01, -2.9803e+00,  ..., -1.2360e+00,
          1.1049e+00,  1.2850e+00]])

In [24]:
mm.shape

torch.Size([32, 100])

In [27]:
foo2 = mm[0] + b1

In [29]:
((mm + b1)[0] == foo2).all()

tensor(True)